server:
  port: 8080

#数据源
sharding:
  jdbc:
    one:
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://10.0.0.17:3306/fate?useSSL=false&nullNamePatternMatchesAll=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useLegacyDatetimeCode=false
      username: xxx
      password: xxx
      connectionTestQuery: select 1


spring:
  redis:
    host: xxxx.xx.xx.xx
    port: 6379
    password: passw0rdredis
    timeout: 3000ms
    database: 0
  rabbitmq:
    addresses: xx.xx.xx.xx:5672
    username: xx
    password: xxxx
    virtual-host: /
    connection-timeout: 15000s
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 2
        max-concurrency: 12
    publisher-confirms: true
    publisher-returns: true #return 的时候代表消息不可达，设置 broker 不自动删除该消息，
    template:
      mandatory: true

wx:
  pay:
    notifyUrl: https://test-c.wanwuyoulian.com/callback/
    sandbox: false

cdn:
  domain: http://cdn.wanwuyoulian.com/
feign:
  merchant:
    ips: xxxxxx
    port: 8081
    domain: https://test-b.wanwuyoulian.com







